#!/usr/bin/env python2

import argparse
from mspacman import app, DEFAULT_HOST, DEFAULT_PORT, DEFAULT_OUTPUT_FILE



if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--host', dest='host', type=str, help='host address',
                        default=DEFAULT_HOST)
    parser.add_argument('-p', '--port', dest='port', type=int, help='port',
                        default=DEFAULT_PORT)
    parser.add_argument('-o', '--output-file', dest='output_file',
                        type=argparse.FileType('w'), help="output-file destination",
                        default=DEFAULT_OUTPUT_FILE)

    args = vars(parser.parse_args())

    app.start_app(**args)

    print args

# :vim:ft=python
